"""add avito webhook events

Revision ID: 3616156865ba
Revises: 20251228_add_webhook_events
Create Date: 2025-12-30 10:35:05.217782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3616156865ba"
down_revision = '20251228_add_webhook_events'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_avito_webhook_events_id'), 'avito_webhook_events', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avito_webhook_events_id'), table_name='avito_webhook_events')
    # ### end Alembic commands ###
