"""messenger webhook tables

Revision ID: 621ce11fbba1
Revises: 3616156865ba
Create Date: 2025-12-30 19:20:09.269503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "621ce11fbba1"
down_revision = '3616156865ba'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avito_chat_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avito_account_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('last_inbound_message_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['avito_account_id'], ['avito_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avito_account_id', 'chat_id', name='uq_avito_chat_state_account_chat')
    )
    op.create_index(op.f('ix_avito_chat_state_avito_account_id'), 'avito_chat_state', ['avito_account_id'], unique=False)
    op.create_index(op.f('ix_avito_chat_state_chat_id'), 'avito_chat_state', ['chat_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avito_chat_state_chat_id'), table_name='avito_chat_state')
    op.drop_index(op.f('ix_avito_chat_state_avito_account_id'), table_name='avito_chat_state')
    op.drop_table('avito_chat_state')
    # ### end Alembic commands ###
