"""add avito_accounts

Revision ID: e59ef775f373
Revises: ca7ca9f5316c
Create Date: 2025-12-29 18:32:13.045037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e59ef775f373"
down_revision = 'ca7ca9f5316c'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avito_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('avito_user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'avito_user_id', name='uq_avito_accounts_project_user')
    )
    op.create_index(op.f('ix_avito_accounts_avito_user_id'), 'avito_accounts', ['avito_user_id'], unique=False)
    op.create_index(op.f('ix_avito_accounts_id'), 'avito_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_avito_accounts_project_id'), 'avito_accounts', ['project_id'], unique=False)
    op.create_index('ix_avito_accounts_project_id_user_id', 'avito_accounts', ['project_id', 'avito_user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_avito_accounts_project_id_user_id', table_name='avito_accounts')
    op.drop_index(op.f('ix_avito_accounts_project_id'), table_name='avito_accounts')
    op.drop_index(op.f('ix_avito_accounts_id'), table_name='avito_accounts')
    op.drop_index(op.f('ix_avito_accounts_avito_user_id'), table_name='avito_accounts')
    op.drop_table('avito_accounts')
    # ### end Alembic commands ###
